const CONSTANTS = {
    SECTORS: {
        'ADBL': 'Commercial Bank', 'EBL': 'Commercial Bank', 'GBIME': 'Commercial Bank', 'HBL': 'Commercial Bank',
        'KBL': 'Commercial Bank', 'MBL': 'Commercial Bank', 'NABIL': 'Commercial Bank', 'NBL': 'Commercial Bank',
        'NICA': 'Commercial Bank', 'NIMB': 'Commercial Bank', 'NMB': 'Commercial Bank', 'PCBL': 'Commercial Bank',
        'PRVU': 'Commercial Bank', 'SANIMA': 'Commercial Bank', 'SBI': 'Commercial Bank', 'SBL': 'Commercial Bank',
        'SCB': 'Commercial Bank', 'CZBIL': 'Commercial Bank', 'MEGA': 'Commercial Bank',

        'CORBL': 'Development Bank', 'EDBL': 'Development Bank', 'GBBL': 'Development Bank', 'JBBL': 'Development Bank',
        'KRBL': 'Development Bank', 'KSBBL': 'Development Bank', 'LBBL': 'Development Bank', 'MDB': 'Development Bank',
        'MLBBL': 'Development Bank', 'MNBBL': 'Development Bank', 'NMLBBL': 'Development Bank', 'SADBL': 'Development Bank',
        'SAPDBL': 'Development Bank', 'SHINE': 'Development Bank', 'SINDU': 'Development Bank', 'SLBBL': 'Development Bank',
        'SWBBL': 'Development Bank', 'GRDBL': 'Development Bank',

        'BFC': 'Finance', 'CFCL': 'Finance', 'CFL': 'Finance', 'GFCL': 'Finance', 'GMFIL': 'Finance',
        'GUFL': 'Finance', 'HFL': 'Finance', 'ICFC': 'Finance', 'JFL': 'Finance', 'MFIL': 'Finance',
        'MPFL': 'Finance', 'NFS': 'Finance', 'PFL': 'Finance', 'PROFL': 'Finance', 'RLFL': 'Finance',
        'SFCL': 'Finance', 'SFC': 'Finance', 'SIFC': 'Finance',

        'ACLBSL': 'Microfinance', 'ACLBSLP': 'Microfinance', 'ALBSL': 'Microfinance', 'CBBL': 'Microfinance',
        'DDBL': 'Microfinance', 'DLBS': 'Microfinance', 'FMDBL': 'Microfinance', 'FOWAD': 'Microfinance',
        'GBLBS': 'Microfinance', 'GILB': 'Microfinance', 'GLBSL': 'Microfinance', 'GMFBS': 'Microfinance',
        'HLBSL': 'Microfinance', 'ILBS': 'Microfinance', 'JBLB': 'Microfinance', 'JSLBB': 'Microfinance',
        'KMCDB': 'Microfinance', 'MLBL': 'Microfinance', 'MLBSL': 'Microfinance', 'MSLB': 'Microfinance',
        'NADEP': 'Microfinance', 'NESDO': 'Microfinance', 'NICLBSL': 'Microfinance', 'NLG': 'Microfinance',
        'NMBMF': 'Microfinance', 'NMFBS': 'Microfinance', 'NUBL': 'Microfinance', 'RSDC': 'Microfinance',
        'SAMAJ': 'Microfinance', 'SKBBL': 'Microfinance', 'SLBSL': 'Microfinance', 'SMFBS': 'Microfinance',
        'SWMF': 'Microfinance', 'ULBSL': 'Microfinance', 'USLB': 'Microfinance', 'VLBS': 'Microfinance',
        'WNLB': 'Microfinance', 'MLBS': 'Microfinance', 'SHLB': 'Microfinance', 'MATRI': 'Microfinance',
        'JOSHI': 'Microfinance', 'SMATA': 'Microfinance', 'ANLB': 'Microfinance', 'UNLB': 'Microfinance',

        'CLI': 'Life Insurance', 'HLI': 'Life Insurance', 'ILI': 'Life Insurance', 'LICN': 'Life Insurance',
        'NLIC': 'Life Insurance', 'NLICL': 'Life Insurance', 'PMLI': 'Life Insurance', 'PRIN': 'Life Insurance',
        'RNLI': 'Life Insurance', 'SJLIC': 'Life Insurance', 'SNLI': 'Life Insurance', 'SRLI': 'Life Insurance',
        'GMLI': 'Life Insurance', 'ALICL': 'Life Insurance', 'GLICL': 'Life Insurance', 'ULI': 'Life Insurance',

        'HEI': 'Non-Life Insurance', 'IGI': 'Non-Life Insurance', 'NICL': 'Non-Life Insurance', 'NIL': 'Non-Life Insurance',
        'NMIC': 'Non-Life Insurance', 'RBCL': 'Non-Life Insurance', 'SALICO': 'Non-Life Insurance', 'SGIC': 'Non-Life Insurance',
        'SICL': 'Non-Life Insurance', 'SPIL': 'Non-Life Insurance', 'UAIL': 'Non-Life Insurance', 'NRIC': 'Non-Life Insurance',
        'NLO': 'Non-Life Insurance', 'PICL': 'Non-Life Insurance', 'PLIC': 'Non-Life Insurance', 'AIL': 'Non-Life Insurance',

        'AHPC': 'Hydropower', 'AKPL': 'Hydropower', 'API': 'Hydropower', 'BARUN': 'Hydropower', 'BNHC': 'Hydropower',
        'BPCL': 'Hydropower', 'CHCL': 'Hydropower', 'CHL': 'Hydropower', 'CKHL': 'Hydropower', 'DHPL': 'Hydropower',
        'DOLTI': 'Hydropower', 'DORDI': 'Hydropower', 'EHPL': 'Hydropower', 'GHL': 'Hydropower', 'GLH': 'Hydropower',
        'HDHPC': 'Hydropower', 'HHL': 'Hydropower', 'HPPL': 'Hydropower', 'HURJA': 'Hydropower', 'KKHC': 'Hydropower',
        'KPCL': 'Hydropower', 'LEC': 'Hydropower', 'MBJC': 'Hydropower', 'MCHL': 'Hydropower', 'MEN': 'Hydropower',
        'MHNL': 'Hydropower', 'MKHC': 'Hydropower', 'MKJC': 'Hydropower', 'NGPL': 'Hydropower', 'NHDL': 'Hydropower',
        'NHPC': 'Hydropower', 'NYADI': 'Hydropower', 'PMHPL': 'Hydropower', 'PPCL': 'Hydropower', 'RADHI': 'Hydropower',
        'RAWA': 'Hydropower', 'RFPL': 'Hydropower', 'RHGCL': 'Hydropower', 'RHPL': 'Hydropower', 'RIDI': 'Hydropower',
        'RURU': 'Hydropower', 'SAHAS': 'Hydropower', 'SHEL': 'Hydropower', 'SHPC': 'Hydropower', 'SJCL': 'Hydropower',
        'SPDL': 'Hydropower', 'SPHL': 'Hydropower', 'SSHL': 'Hydropower', 'SGHC': 'Hydropower', 'TAMOR': 'Hydropower',
        'TPC': 'Hydropower', 'UHEWA': 'Hydropower', 'UMHL': 'Hydropower', 'UNHPL': 'Hydropower', 'UPCL': 'Hydropower',
        'UPPER': 'Hydropower', 'USHEC': 'Hydropower', 'MKHL': 'Hydropower', 'MAKAR': 'Hydropower', 'MEHL': 'Hydropower',
        'MHL': 'Hydropower', 'MHCL': 'Hydropower', 'MEL': 'Hydropower', 'MKCL': 'Hydropower', 'MSHL': 'Hydropower',
        'BHPL': 'Hydropower', 'BEDC': 'Hydropower', 'BHDC': 'Hydropower', 'CHDC': 'Hydropower', 'CITY': 'Hydropower',
        'CREST': 'Hydropower', 'CYCL': 'Hydropower', 'ENL': 'Hydropower', 'GVL': 'Hydropower',
        'IHL': 'Hydropower', 'MANDU': 'Hydropower', 'MMKJL': 'Hydropower',
        'NWCL': 'Hydropower', 'OMPL': 'Hydropower', 'PHCL': 'Hydropower', 'PPL': 'Hydropower',
        'SIKLES': 'Hydropower', 'SMH': 'Hydropower', 'SMHL': 'Hydropower', 'SMB': 'Hydropower',
        'SPL': 'Hydropower', 'TSHL': 'Hydropower', 'TVCL': 'Hydropower', 'ULHC': 'Hydropower', 'VLUCL': 'Hydropower',
        'GSY': 'Hydropower', 'BHL': 'Hydropower', 'SMPDA': 'Hydropower',

        'CGH': 'Hotels', 'OHL': 'Hotels', 'SHL': 'Hotels', 'TRH': 'Hotels', 'YHL': 'Hotels', 'KDL': 'Hotels',

        'BNL': 'Manufacturing', 'BNT': 'Manufacturing', 'BSL': 'Manufacturing', 'BSM': 'Manufacturing',
        'FHL': 'Manufacturing', 'GRU': 'Manufacturing', 'HDL': 'Manufacturing', 'JSM': 'Manufacturing',
        'NKU': 'Manufacturing', 'NVG': 'Manufacturing', 'RJM': 'Manufacturing', 'SRS': 'Manufacturing',
        'UNL': 'Manufacturing', 'SHIVM': 'Manufacturing', 'HBT': 'Manufacturing', 'NFD': 'Manufacturing',
        'NBBU': 'Manufacturing', 'NSM': 'Manufacturing', 'NTL': 'Manufacturing', 'SBPP': 'Manufacturing',
        'AVU': 'Manufacturing', 'AVYAN': 'Manufacturing', 'BGWT': 'Manufacturing',
        'SARBTM': 'Manufacturing', 'SONA': 'Manufacturing', 'GCIL': 'Manufacturing',

        'BBC': 'Trading', 'NTC': 'Telecom', 'STC': 'Trading',

        'CIT': 'Investment', 'HIDCL': 'Investment', 'NIFRA': 'Investment', 'NRN': 'Investment',
        'NABBC': 'Investment', 'HATHY': 'Investment',

        'USHL': 'Others', 'AHL': 'Others', 'MERO': 'Others', 'UMRH': 'Others',
        'HRL': 'Others',
    },

    SECTOR_COLORS: {
        'Commercial Bank': '#3b82f6',
        'Development Bank': '#6366f1',
        'Finance': '#8b5cf6',
        'Microfinance': '#a855f7',
        'Life Insurance': '#ec4899',
        'Non-Life Insurance': '#f43f5e',
        'Hydropower': '#14b8a6',
        'Hotels': '#f59e0b',
        'Manufacturing': '#84cc16',
        'Trading': '#06b6d4',
        'Telecom': '#0ea5e9',
        'Investment': '#6366f1',
        'Others': '#64748b',
    },
    STAR: `<svg width="20" style="vertical-align: sub;" title="At 10% circuit" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path d="M50 10 L61 39 92 39 66 59 76 90 50 72 24 90 34 59 8 39 39 39Z" fill="green" stroke="black" stroke-width="2"/>
</svg>`,
    REDSTAR: `<svg width="20" style="vertical-align: sub;" title="At 10% circuit" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path d="M50 10 L61 39 92 39 66 59 76 90 50 72 24 90 34 59 8 39 39 39Z" fill="red" stroke="black" stroke-width="2"/>
</svg>`,
    COLORS: {
        GREEN: '#026818',
        RED: '#970101',
        NEUTRAL: '#333a56',
        GREEN_SOFT: 'rgb(197 255 209)'
    },
    VENDORS: [
        { key: 'nepse', name: 'Nepal Stock Exchange', site: 'https://www.nepalstock.com.np/company/detail/{TICKER}?source=resiliencia' },
        { key: 'share-sansar', name: 'Share Sansar', site: 'https://www.sharesansar.com/company/{TICKER}?source=resiliencia' },
        { key: 'nepse-alpha', name: 'Nepse Alpha', site: 'https://www.nepsealpha.com/search?q={TICKER}&source=resiliencia' },
        { key: 'chukul', name: 'Chukul', site: 'https://chukul.com/stock-profile?symbol={TICKER}&source=resiliencia' },
    ],
    NEPSEIDS: {
        'USHL': 9192,
        'ACLBSL': 2790,
        'ACLBSLP': 2791,
        'ANLB': 9161,
        'ADBL': 397,
        'API': 697,
        'AKPL': 2757,
        'AHPC': 360,
        'AVU': 211,
        'ALBSL': 2807,
        'AHL': 9150,
        'AVYAN': 8117,
        'BHL': 8055,
        'BHPL': 9135,
        'BARUN': 686,
        'BFC': 227,
        'BGWT': 9214,
        'BEDC': 9171,
        'BHDC': 8075,
        'BSL': 217,
        'BBC': 156,
        'BNL': 195,
        'BNT': 213,
        'BNHC': 8032,
        'BPCL': 153,
        'BSM': 205,
        'CHDC': 3946,
        'CFCL': 245,
        'CGH': 2917,
        'CBBL': 164,
        'CHL': 2766,
        'CHCL': 154,
        'CKHL': 9232,
        'CIT': 210,
        'CLI': 9209,
        'CITY': 9173,
        'CORBL': 450,
        'CREST': 9252,
        'CFL': 361,
        'CYCL': 8065,
        'DDBL': 163,
        'DLBS': 8123,
        'DHPL': 2754,
        'DOLTI': 9170,
        'DORDI': 8070,
        'EHPL': 8131,
        'ENL': 8034,
        'EBL': 137,
        'EDBL': 274,
        'FMDBL': 490,
        'FHL': 228,
        'FOWAD': 2758,
        'GMFBS': 2815,
        'GBBL': 417,
        'GSY': 9248,
        'GHL': 2806,
        'GCIL': 9193,
        'GBIME': 341,
        'GILB': 705,
        'GFCL': 232,
        'GRU': 207,
        'GBLBS': 583,
        'GRDBL': 2744,
        'GVL': 8045,
        'GLH': 2924,
        'GMLI': 9246,
        'GMFIL': 263,
        'GLBSL': 2826,
        'GUFL': 204,
        'HBT': 215,
        'HATHY': 9213,
        'HDHPC': 2880,
        'HURJA': 2824,
        'HBL': 134,
        'HDL': 235,
        'HEI': 179,
        'HFL': 441,
        'HHL': 8076,
        'HLBSL': 693,
        'HLI': 393,
        'HPPL': 2767,
        'HRL': 9234,
        'HIDCL': 2742,
        'ILI': 9184,
        'ICFC': 273,
        'IGI': 186,
        'ILBS': 2832,
        'IHL': 9176,
        'JFL': 250,
        'JSLBB': 695,
        'JBLB': 4951,
        'JOSHI': 2789,
        'JBBL': 418,
        'JSM': 209,
        'KMCDB': 593,
        'KPCL': 2787,
        'KDL': 9151,
        'KSBBL': 459,
        'KRBL': 428,
        'KKHC': 2751,
        'KBL': 142,
        'LEC': 2903,
        'LICN': 188,
        'LBBL': 358,
        'MBL': 140,
        'MBJC': 8031,
        'MLBL': 401,
        'MLBSL': 2925,
        'MSLB': 2768,
        'MKHL': 9167,
        'MKJC': 8005,
        'MAKAR': 9166,
        'MEHL': 9203,
        'MHL': 8102,
        'MANDU': 9212,
        'MFIL': 516,
        'MLBS': 8018,
        'MMKJL': 9217,
        'MATRI': 694,
        'MKHC': 9149,
        'MCHL': 9175,
        'MERO': 1741,
        'MSHL': 9215,
        'MDB': 371,
        'MLBBL': 601,
        'MEL': 9179,
        'MHCL': 9158,
        'MEN': 2913,
        'MHNL': 2811,
        'MNBBL': 474,
        'MKCL': 9230,
        'MPFL': 471,
        'NABIL': 131,
        'NADEP': 2784,
        'NABBC': 172,
        'NMFBS': 2746,
        'NHPC': 152,
        'NLICL': 178,
        'NIL': 183,
        'NBL': 517,
        'NBBU': 233,
        'NTC': 307,
        'NFD': 151,
        'NFS': 194,
        'NHDL': 2769,
        'NIFRA': 2919,
        'NICL': 176,
        'NIMB': 132,
        'NKU': 222,
        'NLIC': 187,
        'NLO': 198,
        'NMIC': 9250,
        'NRIC': 2881,
        'NRM': 9183,
        'SBI': 135,
        'NSM': 200,
        'NTL': 158,
        'NVG': 201,
        'NWCL': 9233,
        'NMLBBL': 396,
        'NESDO': 8041,
        'NGPL': 2743,
        'NICA': 139,
        'NICLBSL': 2887,
        'NUBL': 163,
        'NLG': 559,
        'NMBMF': 704,
        'NMB': 238,
        'NRN': 2898,
        'NYADI': 8026,
        'OMPL': 9256,
        'OHL': 149,
        'PMHPL': 2786,
        'PPCL': 2813,
        'PHCL': 8133,
        'PPL': 8122,
        'PFL': 236,
        'PRVU': 255,
        'PRIN': 184,
        'PMLI': 2915,
        'PCBL': 357,
        'PROFL': 338,
        'RADHI': 2776,
        'RJM': 203,
        'RHGCL': 8108,
        'RBCL': 177,
        'RHPL': 2841,
        'RAWA': 9181,
        'RNLI': 9199,
        'RLFL': 587,
        'RIDI': 610,
        'RFPL': 8066,
        'RSDC': 2748,
        'RURU': 2935,
        'SALICO': 185,
        'SAHAS': 8021,
        'STC': 155,
        'SAMAJ': 4965,
        'SMATA': 2761,
        'SFC': 221,
        'SPC': 8025,
        'SMPDA': 2896,
        'SFCL': 256,
        'SLBSL': 2804,
        'SKBBL': 574,
        'SANIMA': 171,
        'SGIC': 2908,
        'SHPC': 591,
        'TAMOR': 9156,
        'SRLI': 5982,
        'SJCL': 2842,
        'SAPDBL': 2860,
        'SARBTM': 9242,
        'SPHL': 8121,
        'SADBL': 472,
        'SICL': 192,
        'SHINE': 473,
        'SSHL': 2907,
        'SHIVM': 2809,
        'SBPP': 226,
        'SIFC': 244,
        'SRS': 230,
        'SHLB': 8132,
        'SPL': 9147,
        'SBL': 145,
        'SPIL': 182,
        'SIKLES': 8126,
        'SINDU': 561,
        'SHEL': 2934,
        'SHL': 147,
        'SONA': 9216,
        'SCB': 133,
        'SNLI': 9201,
        'SMHL': 9146,
        'SMH': 9148,
        'SMB': 2771,
        'SJLIC': 403,
        'SWMF': 706,
        'SWBBL': 268,
        'SMFBS': 2829,
        'SLBBL': 545,
        'SGHC': 8100,
        'SPDL': 2759,
        'TRH': 148,
        'TPC': 8022,
        'TSHL': 9194,
        'TVCL': 9218,
        'UNL': 219,
        'UNHPL': 2831,
        'UNLB': 9140,
        'UAIL': 180,
        'UMRH': 2914,
        'UMHL': 2760,
        'UPCL': 2810,
        'USLB': 2774,
        'ULBSL': 8063,
        'UHEWA': 8099,
        'ULHC': 9208,
        'USHEC': 8104,
        'UPPER': 2792,
        'VLBS': 687,
        'VLUCL': 9225,
        'WNLB': 2781,
        'YHL': 146,
    }
};
